
package medibuddy.interfaces;


import medibuddy.model.Familiar; 
import medibuddy.service.FamiliarService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import javax.swing.DefaultComboBoxModel;
import medibuddy.model.AdultoMayor; //Importar AdultoMayor
import medibuddy.service.AdultoMayorService; //

public class JFamiliares extends javax.swing.JFrame {
    
    //Creamos al familiar y al adulto
    private final FamiliarService familiarService = new FamiliarService();
    private final AdultoMayorService adultoService = new AdultoMayorService();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFamiliares.class.getName());

    
    // Variable para guardar la lista de adulto de la DB 
    private List<AdultoMayor> listaAdultos;
    
    public JFamiliares() {
        initComponents();
        cargarAdultosEnCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        cnbAdulto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Gestion Familiares");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Familiar Asignado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Telefono:");

        jLabel4.setText("Familiar Asignado:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(111, 207, 123));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 204, 255));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTelefono))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNombre))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cnbAdulto, 0, 260, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnRegresar)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRegresar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cnbAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Familiar para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Obtener el ID del Familiar seleccionado
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int idFamiliar = (int) model.getValueAt(filaSeleccionada, 0);

        int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro que desea eliminar al Familiar con ID: " + idFamiliar + "?", 
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                //Buscar la entidad para pasarla al método delete de Hibernate
                Familiar familiarAEliminar = familiarService.buscarFamiliarPorId(idFamiliar);
                
                if (familiarAEliminar != null) {
                    //Llama al Service para eliminar de la DB
                    familiarService.eliminarFamiliar(familiarAEliminar);
                    
                    JOptionPane.showMessageDialog(this, "Familiar eliminado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    cargarTabla(); // Recargar datos
                    btnLimpiarActionPerformed(null);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar el Familiar.", "Error de DB", JOptionPane.ERROR_MESSAGE);
                logger.log(Level.SEVERE, "Fallo al eliminar Familiar", e);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNombre.setText("");
        txtTelefono.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombre.getText().trim();
        String telefono = txtTelefono.getText().trim();
        int indiceSeleccionado = cnbAdulto.getSelectedIndex();
        
        if (nombre.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe llenar Nombre y Teléfono.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (indiceSeleccionado <= 0) { // Índice 0 es "--- Seleccione un Adulto ---"
            JOptionPane.showMessageDialog(this, "Debe seleccionar el Adulto Mayor a asignar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Obtener el Adulto Mayor seleccionado
            // El índice del ComboBox corresponde al índice de listaAdultos - 1 (por el elemento inicial)
            AdultoMayor adultoAsignado = listaAdultos.get(indiceSeleccionado - 1); // 👈 CUIDADO CON EL ÍNDICE
            
            // Crear el objeto Familiar
            // Asegúrate que tu constructor de Familiar reciba el AdultoMayor
            Familiar nuevoFamiliar = new Familiar(nombre, "Familiar", telefono, "Parentesco NO Capturado en GUI", adultoAsignado);
            
            // Guardar en la DB
            familiarService.crearFamiliar(nuevoFamiliar);
            
            JOptionPane.showMessageDialog(this, "Familiar registrado y asignado a " + adultoAsignado.getNomUsuario() + ".", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            cargarTabla(); 
            btnLimpiarActionPerformed(null);
            
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Error de selección en el Combo Box.", "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Error de índice al obtener Adulto Mayor", e);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar Familiar.", "Error de DB", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Fallo al agregar Familiar", e);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        int indiceCombo = cnbAdulto.getSelectedIndex();
        
        if(txtNombre.getText().trim().isEmpty() || txtTelefono.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Llena primero los campos antes de actualizar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Familiar de la tabla para actualizar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (indiceCombo <= 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el Adulto Mayor a asignar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            //Obtener el ID del Familiar seleccionado en la tabla
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int idFamiliar = (int) model.getValueAt(filaSeleccionada, 0); 
            
            //Buscar la entidad Familiar en la DB
            Familiar familiarExistente = familiarService.buscarFamiliarPorId(idFamiliar);
            
            //Obtener el Adulto Mayor seleccionado del ComboBox
            AdultoMayor nuevoAdulto = listaAdultos.get(indiceCombo - 1); // El índice 0 es el mensaje de selección
            
            if (familiarExistente != null) {
                // 4. Actualizar los datos del objeto
                familiarExistente.setNomUsuario(txtNombre.getText().trim());
                familiarExistente.setTelefono(txtTelefono.getText().trim());
                familiarExistente.setAdultoMayorAsociado(nuevoAdulto); // 👈 Reasignar el Adulto Mayor

                //Guardar los cambios en la DB (Hibernate hace un merge)
                familiarService.actualizarFamiliar(familiarExistente);
                
                JOptionPane.showMessageDialog(this, "Familiar y asignación actualizados con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarTabla(); // Recargar datos
                btnLimpiarActionPerformed(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar. Verifique que los campos estén llenos.", "Error de DB", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Fallo al actualizar Familiar", e);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        //Ocultar la ventana actual (JAdultosMayores)
    this.dispose(); // O this.setVisible(false);

    //Crear y mostrar la ventana del Menú Principal
    try {
        // Reemplaza JMenuPrincipal() con el nombre real de tu clase de Menú Principal
        medibuddy.interfaces.JMenuPrincipal menu = new medibuddy.interfaces.JMenuPrincipal();
        menu.setVisible(true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "No se pudo cargar el Menú Principal.", "Error de Navegación", JOptionPane.ERROR_MESSAGE);
        logger.log(Level.SEVERE, "Fallo al abrir el Menú Principal", e);
    }
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cargarAdultosEnCombo() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        
        try {
            //Obtener la lista de Adultos Mayores de la DB
            listaAdultos = adultoService.listarAdultosMayores();
            
            if (listaAdultos.isEmpty()) {
                model.addElement("No hay Adultos Mayores registrados");
                cnbAdulto.setEnabled(false);
            } else {
                //Llenar el modelo del ComboBox con el Nombre (y opcionalmente el ID)
                model.addElement("--- Seleccione un Adulto ---"); // Opción por defecto
                for (AdultoMayor am : listaAdultos) {
                    model.addElement(am.getNomUsuario() + " (ID: " + am.getIdUsuario() + ")");
                }
                cnbAdulto.setEnabled(true);
            }
            
            //Asignar el modelo al JComboBox
            cnbAdulto.setModel(model);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la lista de Adultos.", "Error de DB", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Fallo al cargar adultos para el combo", e);
        }
    }
    
    private void cargarTabla() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Limpiar filas

        try {
            List<Familiar> familiares = familiarService.listarFamiliares();
            
            for (Familiar f : familiares) {
                // Obtener el nombre del Adulto Mayor asignado.
                String nombreAdulto = (f.getAdultoMayorAsociado() != null) ? f.getAdultoMayorAsociado().getNomUsuario() : "NO ASIGNADO";
                                      
                model.addRow(new Object[]{
                    f.getIdUsuario(), 
                    f.getNomUsuario(),
                    f.getTelefono(),
                    nombreAdulto // 👈 Mostrar el nombre del Adulto Mayor
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos de Familiares.", "Error de DB", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Fallo al cargar tabla de Familiares", e);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFamiliares().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cnbAdulto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
